Capigraph, UI update (#79)
capigraph, uri->url, UI: Svelte 5 and diagrams

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -40,6 +40,19 @@ jobs:
         COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: goveralls -coverprofile=/var/tmp/capillaries.p -service=github
   
+    - name: pkg/capigraph test coverage threshold check
+      env:
+          TESTCOVERAGE_THRESHOLD: 93.9
+      run: |
+            go test -v ./pkg/capigraph/... -coverprofile coverage.out -covermode count
+            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 >= $2)}') )); then
+                echo -e "\033[32mOK: $totalCoverage >= $TESTCOVERAGE_THRESHOLD\033[0m"
+            else
+                echo -e "\033[31mFAILED: $totalCoverage < $TESTCOVERAGE_THRESHOLD. Cover more with unit tests or adjust threshold to a lower value.\033[0m"
+                exit 1
+            fi
+
     - name: pkg/cql test coverage threshold check
       env:
           TESTCOVERAGE_THRESHOLD: 87.6
