AMQP10 brokers tests pass, capimq reasonable (figure out heartbeat for fannie_mae_quicktest_local_fs_multi/2/02_loan_ids/8

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -81,7 +81,7 @@ jobs:
 
     - name: pkg/custom/tag_and_denormalize test coverage threshold check
       env:
-          TESTCOVERAGE_THRESHOLD: 76.1
+          TESTCOVERAGE_THRESHOLD: 78.5
       run: |
             go test -v ./pkg/custom/tag_and_denormalize/... -coverprofile coverage.out -covermode count
             totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
@@ -94,7 +94,7 @@ jobs:
 
     - name: pkg/dpc test coverage threshold check
       env:
-          TESTCOVERAGE_THRESHOLD: 85.7
+          TESTCOVERAGE_THRESHOLD: 80.0
       run: |
             go test -v ./pkg/dpc/... -coverprofile coverage.out -covermode count
             totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
@@ -110,6 +110,19 @@ jobs:
           TESTCOVERAGE_THRESHOLD: 98.0
       run: |
             go test -v ./pkg/eval/... -coverprofile coverage.out -covermode count
+            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 >= $2)}') )); then
+                echo -e "\033[32mOK: $totalCoverage >= $TESTCOVERAGE_THRESHOLD\033[0m"
+            else
+                echo -e "\033[31mFAILED: $totalCoverage < $TESTCOVERAGE_THRESHOLD. Cover more with unit tests or adjust threshold to a lower value.\033[0m"
+                exit 1
+            fi
+
+    - name: pkg/mq_message_broker test coverage threshold check
+      env:
+          TESTCOVERAGE_THRESHOLD: 86.2
+      run: |
+            go test -v ./pkg/mq_message_broker/... -coverprofile coverage.out -covermode count
             totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
             if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 >= $2)}') )); then
                 echo -e "\033[32mOK: $totalCoverage >= $TESTCOVERAGE_THRESHOLD\033[0m"
