Cleanup

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -53,6 +53,19 @@ jobs:
                 exit 1
             fi
 
+    - name: pkg/capimq_message_broker test coverage threshold check
+      env:
+          TESTCOVERAGE_THRESHOLD: 82.4
+      run: |
+            go test -v ./pkg/capimq_message_broker/... -coverprofile coverage.out -covermode count
+            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 >= $2)}') )); then
+                echo -e "\033[32mOK: $totalCoverage >= $TESTCOVERAGE_THRESHOLD\033[0m"
+            else
+                echo -e "\033[31mFAILED: $totalCoverage < $TESTCOVERAGE_THRESHOLD. Cover more with unit tests or adjust threshold to a lower value.\033[0m"
+                exit 1
+            fi
+
     - name: pkg/cql test coverage threshold check
       env:
           TESTCOVERAGE_THRESHOLD: 88.1
@@ -118,22 +131,9 @@ jobs:
                 exit 1
             fi
 
-    - name: pkg/mq_message_broker test coverage threshold check
-      env:
-          TESTCOVERAGE_THRESHOLD: 86.2
-      run: |
-            go test -v ./pkg/mq_message_broker/... -coverprofile coverage.out -covermode count
-            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
-            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 >= $2)}') )); then
-                echo -e "\033[32mOK: $totalCoverage >= $TESTCOVERAGE_THRESHOLD\033[0m"
-            else
-                echo -e "\033[31mFAILED: $totalCoverage < $TESTCOVERAGE_THRESHOLD. Cover more with unit tests or adjust threshold to a lower value.\033[0m"
-                exit 1
-            fi
-
     - name: pkg/sc test coverage threshold check
       env:
-          TESTCOVERAGE_THRESHOLD: 89.6
+          TESTCOVERAGE_THRESHOLD: 89.5
       run: |
             go test -v ./pkg/sc/... -coverprofile coverage.out -covermode count
             totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
