Fixes; gocqlmem; go 1.26.1 (#94)

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -19,7 +19,7 @@ jobs:
     - name: Set up Go
       uses: actions/setup-go@v3
       with:
-        go-version: '1.25'
+        go-version: '1.26.1'
 
     - name: Build
       run: go build -v ./...
@@ -27,12 +27,12 @@ jobs:
     - name: golangci-lint
       uses: golangci/golangci-lint-action@v8
       with:
-        version: v2.5.0
+        version: v2.11.4
         args: --verbose --timeout 10m --fix=false --config=.golangci.yml ./pkg/...
 
     - name: Generate coverage report for coveralls.io
       run: |
-        go test -coverprofile=/var/tmp/capillaries.p.tmp -cover $(find ./ -name '*_test.go' -printf "%h\n" | sort -u)
+        go test -coverprofile=/var/tmp/capillaries.p.tmp -cover $(find ./ -name '*_test.go' ! -wholename './pkg/api*' ! -wholename './pkg/gocql*' -printf "%h\n" | sort -u)
         cat /var/tmp/capillaries.p.tmp | grep -v "donotcover" > /var/tmp/capillaries.p
 
     - name: Send coverage to coveralls.io
@@ -120,7 +120,7 @@ jobs:
 
     - name: pkg/eval test coverage threshold check
       env:
-          TESTCOVERAGE_THRESHOLD: 98.0
+          TESTCOVERAGE_THRESHOLD: 96.9
       run: |
             go test -v ./pkg/eval/... -coverprofile coverage.out -covermode count
             totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
@@ -131,9 +131,22 @@ jobs:
                 exit 1
             fi
 
+    - name: pkg/eval_capi test coverage threshold check
+      env:
+          TESTCOVERAGE_THRESHOLD: 99.5
+      run: |
+            go test -v ./pkg/eval_capi/... -coverprofile coverage.out -covermode count
+            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 >= $2)}') )); then
+                echo -e "\033[32mOK: $totalCoverage >= $TESTCOVERAGE_THRESHOLD\033[0m"
+            else
+                echo -e "\033[31mFAILED: $totalCoverage < $TESTCOVERAGE_THRESHOLD. Cover more with unit tests or adjust threshold to a lower value.\033[0m"
+                exit 1
+            fi
+
     - name: pkg/sc test coverage threshold check
       env:
-          TESTCOVERAGE_THRESHOLD: 89.5
+          TESTCOVERAGE_THRESHOLD: 89.7
       run: |
             go test -v ./pkg/sc/... -coverprofile coverage.out -covermode count
             totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
